name: CD Pipeline

on:
  workflow_run:
    workflows:
      - CI Pipeline
    types:
      - completed

jobs:
  deploy-1:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to EC2-1
      run: |
        mkdir -p ~/midterm
        echo "${{ secrets.SSH_KEY }}" > ~/midterm/awsLab.pem
        chmod 600 ~/midterm/awsLab.pem
        ssh -o StrictHostKeyChecking=no ssh -i "awsLab.pem" ubuntu@ec2-54-209-97-163.compute-1.amazonaws.com << EOF
        sudo docker stop cicd_m || true
        sudo docker rm cicd_m || true
        sudo docker pull ${{ secrets.DOCKER_USERNAME }}/cicd_m:latest
        sudo docker run -d --name cicd_m -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/cicd_m:latest
        EOF

  deploy-2:
    runs-on: ubuntu-latest
    needs: deploy-1
    steps:
    - name: Deploy to EC2-2
      run: |
        mkdir ~/midterm/awsLab.pem
        echo "${{ secrets.SSH_KEY2 }}" > ~/midterm/awsLab.pem
        chmod 600 ~/midterm/awsLab.pem
        ssh -o StrictHostKeyChecking=no -i ssh -i "awsLab.pem" ubuntu@ec2-98-81-184-25.compute-1.amazonaws.com << EOF
        sudo docker stop cicd_m || true
        sudo docker rm cicd_m || true
        sudo docker pull ${{ secrets.DOCKER_USERNAME }}/cicd_m:latest
        sudo docker run -d --name cicd_m -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/cicd_m:latest
        EOF
